### ISSUE TITLE
Need to add netCDF-4 as a requirement

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#1]
Need to add netCDF-4 or scipy as a requirement for creating netcdf files

**Comment by iamsaswata** [comment]
Thanks for highlighting. I was able to recreate this error: `ImportError: matplotlib is required for plotting when the default backend matplotlib is selected.`   

Now scipy is added in the [requirements](https://github.com/iamsaswata/imdlib/blob/master/requirements.txt) with 7ec7f071a607fe96e4ce69b6e27dc7c2572e50bb.

**Comment by pratiman-91** [comment]
Thanks
