### ISSUE TITLE
Hi! Still your code have some problems

### ISSUE THREAD

**Issue by SubhadipDatta** [iamsaswata/imdlib#15]
It can't write tiff file with CRS. and not ignoring no data. I am also a GIS developer and want to collaborate with you to solve this also add some more features to this.

**Comment by iamsaswata** [comment]
Thanks @SubhadipDatta  for highlighting the issue of CRS in tiff file format. It has been resolved with the latest update (v.0.1.12). I am attaching the results (see the attached jupyter notebook example) of tiff CRS using the latest IMDLIB updates. You can also check and confirm for the same.

We will be happy to collaborate with you on useful features for the IMDLIB. First, you can present your ideas as an issue to this repository. If it is aligned with the vision of the package, we will request you to make a pull request to the IMDLIB with the newer features. 

![gh_issue_15](https://user-images.githubusercontent.com/15724605/167253188-e1b88093-6e17-43a2-8557-f702ebd2e0e0.jpg)

**Comment by SubhadipDatta** [comment]
Your codes are more object-oriented, but I do simple coding. Let me deep review your codes. Is there any option for personal messaging?

**Comment by SubhadipDatta** [comment]
For now, set nodata for geotiff output.

**Comment by iamsaswata** [comment]
This is the standard practice in Python community. There is no hurry, you can take your time to get familiar with the standard practices. Sorry to tell you that we won't be available during this time for personal messages.
