### ISSUE TITLE
for plotting in xarray need to have matplotlib as a requirement

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#2]
Need to add matplotlib as a requirement

**Comment by iamsaswata** [comment]
Thanks for highlighting. I was able to recreate this error: `ImportError: matplotlib is required for plotting when the default backend matplotlib is selected.`   

Now matplotlib is added in the [requirements](https://github.com/iamsaswata/imdlib/blob/master/requirements.txt) with 7ec7f071a607fe96e4ce69b6e27dc7c2572e50bb.

**Comment by pratiman-91** [comment]
Thanks
