### ISSUE TITLE
Data file download failed

### ISSUE THREAD

**Issue by pradeep2c1** [iamsaswata/imdlib#21]
I was trying to download imd gridded data, but got the error:
File Download Failed! Error: 404 Client Error: Not Found for url: https://imdpune.gov.in/Clim_Pred_LRF_New/rainfall.php
![image](https://user-images.githubusercontent.com/104556177/219412373-873c11c5-b6dc-4ca6-af19-03e79875f668.png)

**Comment by iamsaswata** [comment]
What version of imdlib you are using?

**Comment by pradeep2c1** [comment]
I downloaded it using conda with python 3.7.9
it is: imdlib-0.1.8.1

**Comment by pradeep2c1** [comment]
Also, actually I want to work with real time data (date-wise)
But there also I got error:
![image](https://user-images.githubusercontent.com/104556177/219428916-9b96b412-f2ba-4e1f-9101-cfb66451827f.png)

**Comment by iamsaswata** [comment]
Yes, real time date (date-wise) will work if you update your imdlib to the newest version. Also, it will solve the earlier error (File Download Failed! Error: 404 Client Error) you were facing. Update the imdlib and make sure it has version 0.1.15 (as of now February, 2023). You can try something like : pip install imdlib==0.1.15 or pip install --force-reinstall -v "imdlib==0.1.15".

**Comment by pradeep2c1** [comment]
Thanks, it worked for downloading yearly data.
But still there is issue with daily data:
![image](https://user-images.githubusercontent.com/104556177/219472451-96f56da2-d91b-4e29-b3cc-421cdf34bda0.png)
![image](https://user-images.githubusercontent.com/104556177/219472578-8d0816af-1cd1-4fd9-87ee-20a30b80f8a6.png)
Can you please help out with this

**Comment by iamsaswata** [comment]
Happy to know it solved your problem.

Regarding your mentioned issue in the last comment " But still there is issue with daily data:", I can confirm you that it is not a problem of the IMDLIB library.  I have attached a screenshot from my notebook for your reference. 

If i have to make it simplt, imd only stores real time daily data for the recent time period (that's why newer date woks, e.g., 2020 in the example), but not the data from long back (that's why 2013 in your example is not working).


![github_imdlib_issue_feb_2023](https://user-images.githubusercontent.com/15724605/219479389-3c86451e-8d1c-4ed6-a468-78a76b9fd3f3.png)

**Comment by iamsaswata** [comment]
Happy it worked for you.  If you need daily data ( which is not real time), it is possible ( take the archive data and extract as per your need). Otherwise, I am not sure. But in practice, real time data are used in real time and historical data for long term applications.

**Comment by pradeep2c1** [comment]
Maybe, my words were not that precise.
I wanted to mean that I want data like for dates 01-04-2001, 02-04-2001, ...

**Comment by iamsaswata** [comment]
That's fine. 
If you can read the data in imdlib, then you can achieve this in two step. Assuming you have the long data in a variable called 'data', (1) you convert it to xarray format by using imdlib function get_xarray() function ( e.g. ds=data.get_xarray())  ( available at documentation site:https://imdlib.readthedocs.io) and finally (2) get your required days ( e.g. 01-04-2001) using xarray slice syntax ( e.g., ds.sel(time='YYYY-MM-DD')).
