### ISSUE TITLE
Clip by Shape files

### ISSUE THREAD

**Issue by ved-ux** [iamsaswata/imdlib#26]
I would like to express my sincere gratitude for the creation of the imdlib Python package. Your dedication to developing this valuable tool has greatly contributed to simplifying data manipulation and analysis, particularly in the context of meteorological data.

How do to trim a rainfall dataset based on a shapefile or the extent of the shapefiles? I want to download data for the Ganga Basin instead of the whole of India.

Thank you.

**Comment by iamsaswata** [comment]
Thank you for your encouraging words. It means a lot.

Regarding clipping shapefiles, it can be done in multiple ways. You can use imdlib's inbuild 'clip' function for this or mayuse external GIS software too. I will briefly describe both the approaches.


1. Using IMDLIB 'CLIP':
       
       Assuming you have already downloaded the data (follow [https://imdlib.readthedocs.io](https://imdlib.readthedocs.io) for the data downloading and opening)
        --------
        > start_yr = 2015
        > end_yr = 2015
        > variable = 'tmax'
        > data = imd.open_data(variable, start_yr, end_yr, 'yearwise')
        > data.clip('shapefile_folder_path/shapefile_name.shp') 

       Now data variable is clliped as per the shapefile. You can use other IMDLIB functionalities to transfer/save it to xarray/netcdf /GeoTIFF as described in the documentation ([https://imdlib.readthedocs.io](https://imdlib.readthedocs.io))

2. External GIS software: 

        First save the data in GeoTIFF  
        > start_yr = 2015
        > end_yr = 2015
        > variable = 'tmax'
        > data = imd.open_data(variable, start_yr, end_yr, 'yearwise')
        > data.to_geotiff('test.tif')

      Then use ArcGIS/QGIS/GDAl as usual on the geotiff data.

**Comment by ved-ux** [comment]
Thank you
