### ISSUE TITLE
Resolution for IMD tmax/tmin data

### ISSUE THREAD

**Issue by y-sheng** [iamsaswata/imdlib#27]
Hi,

I can see the latest version is now supporting the 0.5 x 0.5 degree data, so when downloading the real-time tmin/tmax data, is there any parameter that should be used to specify which resolution is needed, or does it automatically downloads 0.5 x 0.5 degree data?  

Thanks in advance

**Comment by iamsaswata** [comment]
Hi @y-sheng, your thoughts on the resolution were correct that means it automatically downloads 0.5 x 0.5 degree data by default. If one needs the 1 degree data, the inbuilt or external remap functions should be used for that.

**Comment by y-sheng** [comment]
Thank you!
