### ISSUE TITLE
Add feature to_geotiff

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#5]
Adding a new feature using https://pratiman-91.github.io/2020/10/06/IMD-grided-to-GeoTIFF.html

**Comment by iamsaswata** [comment]
Thanks for the suggestion. It has been added to the library using e6ac4fd6f266dcce12cb6138079d9b8e3ceb3911.
This modification is added at https://github.com/iamsaswata/imdlib/blob/f346a8efe99864ae0e4aad83217ee8f45c2e5fc1/imdlib/core.py#L195-L210

Now we can use:
```python
# Convert to GeoTIFF format
data.to_geotiff(file_name, out_dir)
```
