### ISSUE TITLE
Add new feature get_data. If a variable is assigned then it should open all the downloaded files as well.

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#6]
CURRENT VERSION:

import imdlib as imd

# Downloading 8 years of rainfall data for India
start_yr = 2010
end_yr = 2018
variable = 'rain' # other options are ('tmin'/ 'tmax')
file_dir = (r'C:\Users\imdlib\Desktop\') #Path to save the files

imd.get_data(variable, start_yr, end_yr, fn_format='yearwise', file_dir=file_dir)

# Opeining the downloaded dataset
data = imd.open_data(variable, start_yr, end_yr,'yearwise', file_dir)

POSSIBLE VERSION:
import imdlib as imd

# Downloading 8 years of rainfall data for India
start_yr = 2010
end_yr = 2018
variable = 'rain' # other options are ('tmin'/ 'tmax')
file_dir = (r'C:\Users\imdlib\Desktop\') #Path to save the files

# download and open dataset
data = imd.get_data(variable, start_yr, end_yr, fn_format='yearwise', file_dir=file_dir)

**Comment by iamsaswata** [comment]
Thanks for such detailed guideline for improving the IMDLIB core functionality. It has been added to the library using e6ac4fd6f266dcce12cb6138079d9b8e3ceb3911.
This modification is added at https://github.com/iamsaswata/imdlib/blob/f346a8efe99864ae0e4aad83217ee8f45c2e5fc1/imdlib/core.py#L486-L487

Now we can use:
```python
import imdlib as imd
start_yr = 2010
end_yr = 2018
variable = 'rain'
file_format = 'yearwise'
file_dir = 'dataFolder'
data = imd.get_data(variable, start_yr, end_yr, fn_format=file_format, file_dir=file_dir)
```
