### ISSUE TITLE
Unable to install on conda for python 3.8.3

### ISSUE THREAD

**Issue by carbform** [iamsaswata/imdlib#7]
I used the library successfully before updating the python version on conda.
Requesting support for python >= 3.7

**Comment by pratiman-91** [comment]
It should be installing. I am not sure how are you trying to install. Maybe you can try:

> pip install imdlib

This should work.
If you still have some problem, then please describe the steps related to the problem.

**Comment by carbform** [comment]
Thank you! 
Using 
`
pip install imdlib` 

worked.  

Earlier I tried installing using 
`conda install -c iamsaswata imdlib`
