### ISSUE TITLE
Adding Climate and Forecasting (CF) metadata convention in to_netcdf 

### ISSUE THREAD

**Issue by pratiman-91** [iamsaswata/imdlib#8]
New Feature to_netcdf must include the CF conventions. This will help to maintain the compatibility in other software.

>https://unidata.github.io/python-training/workshop/XArray/xarray-and-cf/

Might be help at later stage.

**Comment by iamsaswata** [comment]
Thanks for this awesome much needed suggestion. Now IMDLIB conforms CF-1.7 conventions.
It has been added to the library using e6ac4fd6f266dcce12cb6138079d9b8e3ceb3911.   
This modification is added at https://github.com/iamsaswata/imdlib/blob/f346a8efe99864ae0e4aad83217ee8f45c2e5fc1/imdlib/core.py#L131-L177

##### IMDLIB now also support latest pyproj CRS conventions too. So, using rioxarray is with IMDLIB is very consistent now.

Output of ncdum -h info on the generated netCDF is shown at [IMDLIB doc](https://saswatanandi.github.io/softwares/imdlib/#netcdf-file-convention).

Final CF checking is also done using [pumatest](https://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl)
and result is show here.
![cf_convention](https://user-images.githubusercontent.com/15724605/103343097-3263cc00-4ab1-11eb-8069-a9bec9b1064a.jpg)
